config/routes.rb
RedmineApp::Application.routes.draw do
  get 'projects/:project_id/wiki/:id/access_control', to: 'wiki_acl#show', as: 'wiki_acl_page'
  patch 'projects/:project_id/wiki/:id/access_control', to: 'wiki_acl#update', as: 'wiki_acl_page_update'
end

app/models/wiki_page_acl.rb
class WikiPageAcl < ActiveRecord::Base
  belongs_to :wiki_page
  belongs_to :user

  validates :access_level, inclusion: { in: %w[view edit] }
  validates :wiki_page_id, uniqueness: { scope: :user_id }

  scope :viewers, -> { where(access_level: %w[view edit]) }
  scope :editors, -> { where(access_level: 'edit') }

  def self.restricted?(wiki_page)
    where(wiki_page_id: wiki_page.id).exists?
  end

  def self.user_can_view?(wiki_page, user)
    return true if user.admin?
    acls = where(wiki_page_id: wiki_page.id)
    return true if acls.empty?
    acls.exists?(user_id: user.id)
  end

  def self.user_can_edit?(wiki_page, user)
    return true if user.admin?
    acls = where(wiki_page_id: wiki_page.id)
    return true if acls.empty?
    acls.exists?(user_id: user.id, access_level: 'edit')
  end
end

app/controllers/wiki_acl_controller.rb
class WikiAclController < ApplicationController
  before_action :find_project
  before_action :find_wiki
  before_action :find_page
  before_action :authorize

  def show
    @acls = WikiPageAcl.where(wiki_page_id: @page.id).index_by(&:user_id)
    @members = @project.members.includes(:user).map(&:user).sort_by(&:name)
    @restricted = @acls.any?
  end

  def update
    WikiPageAcl.where(wiki_page_id: @page.id).delete_all

    if params[:restricted] == '1' && params[:users].present?
      params[:users].each do |user_id, attrs|
        next unless attrs[:enabled] == '1'
        WikiPageAcl.create!(
          wiki_page_id: @page.id,
          user_id: user_id.to_i,
          access_level: attrs[:access_level].presence || 'view'
        )
      end
    end

    flash[:notice] = l(:notice_successful_update)
    redirect_to wiki_acl_page_path(@project, @page.title)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_wiki
    @wiki = @project.wiki
    render_404 unless @wiki
  end

  def find_page
    @page = @wiki.find_page(params[:id])
    render_404 unless @page
  end
end

app/views/settings/_wiki_acl_settings.html.erb
<div class="box tabular settings">
  <p>
    <label for="settings_enabled"><%= l(:wiki_acl_plugin_enabled) %></label>
    <%= hidden_field_tag 'settings[enabled]', '0' %>
    <%= check_box_tag 'settings[enabled]', '1', @settings['enabled'] != '0', id: 'settings_enabled' %>
  </p>
</div>

app/views/wiki_acl/show.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'wiki_acl', plugin: 'redmine_wiki_acl' %>
<% end %>

<h2><%= @page.title %> &mdash; <%= l(:wiki_acl_access_control) %></h2>

<div class="wiki-acl-tabs">
  <%= link_to l(:label_wiki), project_wiki_page_path(@project, @page.title) %>
  <% if User.current.allowed_to?(:edit_wiki_pages, @project) %>
    | <%= link_to l(:button_edit), edit_project_wiki_page_path(@project, @page.title) %>
  <% end %>
  | <%= link_to l(:label_history), history_project_wiki_page_path(@project, @page.title) %>
  | <strong><%= "🔒 #{l(:wiki_acl_access_control)}" %></strong>
</div>

<%= form_tag(wiki_acl_page_update_path(@project, @page.title), method: :patch) do %>
  <div class="box">
    <p>
      <label>
        <%= check_box_tag 'restricted', '1', @restricted, id: 'wiki_acl_restricted' %>
        <strong><%= l(:wiki_acl_restrict_access) %></strong>
      </label>
    </p>

    <div id="wiki_acl_user_list" style="<%= 'display:none;' unless @restricted %>">
      <table class="list wiki-acl-table">
        <thead>
          <tr>
            <th></th>
            <th><%= l(:label_user) %></th>
            <th><%= l(:wiki_acl_access_level) %></th>
          </tr>
        </thead>
        <tbody>
          <% @members.each do |user| %>
            <% acl = @acls[user.id] %>
            <tr class="<%= cycle('odd', 'even') %>">
              <td class="checkbox">
                <%= check_box_tag "users[#{user.id}][enabled]", '1', acl.present?,
                    id: "user_#{user.id}" %>
              </td>
              <td>
                <label for="user_<%= user.id %>"><%= user.name %></label>
              </td>
              <td>
                <%= select_tag "users[#{user.id}][access_level]",
                    options_for_select(
                      [[l(:wiki_acl_view), 'view'], [l(:wiki_acl_edit), 'edit']],
                      acl&.access_level || 'view'
                    ),
                    class: 'wiki-acl-level-select' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <p class="wiki-acl-notes">
      <em class="info"><%= l(:wiki_acl_admin_note) %></em><br/>
      <em class="info"><%= l(:wiki_acl_unrestrict_note) %></em>
    </p>

    <p><%= submit_tag l(:wiki_acl_save), class: 'btn btn-primary' %></p>
  </div>
<% end %>

<%= javascript_tag do %>
  document.getElementById('wiki_acl_restricted').addEventListener('change', function() {
    var list = document.getElementById('wiki_acl_user_list');
    list.style.display = this.checked ? '' : 'none';
  });
<% end %>